
#define USE_ADDLOG_ARRAY 1
#define CLASS_NGRAM 1
#define MFCC_SINCOS_TABLE 1
#define USE_MBR 1
#define STDC_HEADERS 1
#define HAVE_UNISTD_H 1
#define HAVE_SOCKLEN_T 1
#define HAVE_STRCASECMP 1
#define HAVE_SLEEP 1
#define HAVE_SYS_SOUNDCARD_H 1
