#!/bin/bash
set -e
set -u

USER=tobby
TEALION_ROOT="/home/${USER}/tealion"; export TEALION
INIT_PATH="${TEALION_ROOT}/etc/init.d"
SUDO="sudo -u $USER"

start () {
	# start TEALION

	# make device_file(work around)
	sudo modprobe snd-pcm-oss
	#cd /dev/
	#sudo rm /dev/dsp
	#sudo ln -s dsp1 dsp

	# make wave_file
	cd /tmp
	if [ ! -L tealion ]; then
		ln -s $TEALION_ROOT/share/voice tealion
	fi

	# make var directory
	DIR_NAMES=("/var/run/tealion" "/var/log/tealion")
	for DIR_NAME in ${DIR_NAMES[@]}; do
		sudo mkdir -p $DIR_NAME
		sudo chown $USER:$USER $DIR_NAME
	done

	$SUDO $INIT_PATH/lifeSoundLog-master start
	$SUDO $INIT_PATH/julius start
	$SUDO $INIT_PATH/lifeSound_client-master start

}

stop () {
	$SUDO $INIT_PATH/lifeSound_client-master stop
	$SUDO $INIT_PATH/julius stop
	$SUDO $INIT_PATH/lifeSoundLog-master stop
}

restart () {
  stop
  start
}

status () {
  ps aux | grep "tealion"
}

help () {
  echo "Usage: $0 {start|stop|restart|status|help}"
}

if [ $# -lt 1 ]; then
    help
    exit 1
fi

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  help)
    help
    ;;
  *)
    help
    exit 1
esac

exit $?
