#!/bin/bash
set -e
set -u

TEALION_ROOT="/home/pi/tealion"; export TEALION
INIT_PATH="$TEALION_ROOT/etc/init.d"
USER_NAME="pi"

export HOYA_API=""

start () {
	# start TEALION

	# make wave_file
	cd /tmp
	if [ ! -L tealion ]; then
		ln -s $TEALION_ROOT/share/voice tealion
	fi

	# make var directory
	DIR_NAMES=("/var/run/tealion" "/var/log/tealion")
	for DIR_NAME in ${DIR_NAMES[@]}; do
		sudo mkdir -p $DIR_NAME
		sudo chown $USER_NAME:$USER_NAME $DIR_NAME
	done

	sudo -u $USER_NAME -i $INIT_PATH/lifeSoundLog start
	$INIT_PATH/julius start
	sudo -u $USER_NAME -i $INIT_PATH/lifeSound_client start

}

stop () {
	sudo -u $USER_NAME -i $INIT_PATH/lifeSound_client stop
	$INIT_PATH/julius stop
	sudo -u $USER_NAME $INIT_PATH/lifeSoundLog stop
}

restart () {
  stop
  start
}

status () {
  ps aux | grep "tealion"
}

help () {
  echo "Usage: $0 {start|stop|restart|status|help}"
}

if [ $# -lt 1 ]; then
    help
    exit 1
fi

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  help)
    help
    ;;
  *)
    help
    exit 1
esac

exit $?
